### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by jameswestcott** [kernie66/homebridge-random-delay-switches#10]
Hi

Is it possible to add the following features:
1. Allow an infinite number of repeats. At the moment I have an automation that turns the switch back on.
2. Allow delay times longer than 24 hours.

**Comment by kernie66** [comment]
Hi,

Thanks for using the plugin. I can add #1 and see what to do about #2. 

Regards,
Kenneth

**Comment by kernie66** [comment]
After some problem with my development environment, I added infinite repetitions.

Longer delays may cause some larger changes. 
- What is the use case for longer delays?
- Cannot Cron be used?
- How much longer than 24 hours would be needed? 48? Much longer?

Regards,
Kenneth

**Comment by jameswestcott** [comment]
Thanks for the update. The use case for the longer delays is to monitor that my hot water tank is working properly...
1. Timer is set for 3 days which when triggered while send an error notification to my phone.
2. When various conditions are met, e.g. all heating elements are working correctly, the timer is reset back to 3 days.

If there was better event trigger logic in HomeKit, then I could probably do it a different way.

**Comment by kernie66** [comment]
Ok, I have checked that longer delays will work. I just have to decide how I may present it in Eve.

Regards,
Kenneth

**Comment by kernie66** [comment]
By the way, if you need a trigger every third day you can use a cron pattern like '0 0 12 */3 * *', which will trigger every third day of the month at noon. This may not give three days at the end of the month, as it references the day of month.

**Comment by jameswestcott** [comment]
I was under the impression that the cron patterns turned the timer on? I need to be able to run the timer for 3 days with the option of resetting the count back to 3 days. The automation I'm trying to capture is 'tell me if my water heater hasn't worked properly for the past 3 days'

**Comment by kernie66** [comment]
Ah, I see. Well, then cron is not the solution. I have added delays up to 10 days and will release a new version soon. Just doing some final checks.

**Comment by jameswestcott** [comment]
That's great. Thanks. On another note, how do I set the heartrate within the homebridge config? Even if I change it in the Eve app, it resets to 15s when homebridge restarts?
