### ISSUE TITLE
Timer not working

### ISSUE THREAD

**Issue by jameswestcott** [kernie66/homebridge-random-delay-switches#11]
Hi,
Since you modified the timer to accommodate days (thank you) there’s some bugs been introduced. I haven’t had time to fully work out what’s going on but happy to if you need me. Issues are:
1. When changing the sliders in Eve app the number of days is ignored. This is even reflected in current timeout value and time left of timer. 
2. Something Is setting the timer to maximum (ie. 10 days). I think it’s when sending an on command to a switch which is already on. 
3. There’s no way of setting the heartbeat value in the config and when reboot homebridge the heartbeat resets to 15s.

**Comment by kernie66** [comment]
Oops, I probably didn't test enough. I will check these. 
I had some issues myself with the heartbeat function, but figured that I could live with it. I will look at it again, though. 

Regards
Kenneth

**Comment by kernie66** [comment]
Addressed issues in release 1.2.1. Also covers last question in #10.
