### ISSUE TITLE
Repeat forever doesn't work

### ISSUE THREAD

**Issue by jameswestcott** [kernie66/homebridge-random-delay-switches#13]
Setting the repeat value to -1 doesn't work in v1.2.0

**Comment by kernie66** [comment]
I cannot replicate that, for me it works. Could you please attach a log of the activation of the switch, e.g. with `cat /var/lib/homebridge/homebridge.log | grep [rR]andomly` or whatever you call the platform.

**Comment by jameswestcott** [comment]
Apologies, between changing versions and what settings were in the config file and what was cached, meant the timer wasn't actually set to -1. It's been resolved now and is working.
