### ISSUE TITLE
Reversible

### ISSUE THREAD

**Issue by jameswestcott** [kernie66/homebridge-random-delay-switches#6]
Great switch with a lot of features. Any chance you can add a reversible feature so the default state is on?

**Comment by jameswestcott** [comment]
plus be able to set a duration larger than 3600s (appreciate may have issues with the slider in the eve app) and be able to set a stateful switch (maybe duration set at 0). You'd pretty much cover off all virtual switch operations then!

**Comment by jameswestcott** [comment]
Thanks for the update. Functionally you get no benefit with having a reversible switch. It’s purely a grammatical thing when interacting with Siri to be able to have the default state as on and be able to turn something off for a period of time.
________________________________

**Comment by mrmay-dev** [comment]
Hello!

The plug-in configuration page is very slow to respond. It can take up to a minute for buttons to respond and form boxes to become active selecting. What data can I collect that would help troubleshoot this. 

All other plug-in pages load normally.
