### ISSUE TITLE
Configuration page is slow to become responsive. 

### ISSUE THREAD

**Issue by mrmay-dev** [kernie66/homebridge-random-delay-switches#9]
Hello!

The plug-in configuration page is very slow to respond. It can take up to a minute for buttons to respond and form boxes to become active selecting. What data can I collect that would help troubleshoot this.

All other plug-in pages load normally.

**Comment by kernie66** [comment]
Hi,

Thanks for using my plug-in. I'm sorry to hear that you have trouble with it. I don't see any delay when I open the configuration on my setup. I have nine different switches and it loads instantly. I do run the plug-in as a child bridge, but I don't see why that should affect the configuration UI. 

The only thing I can think of straight away is a memory issue. Can you check if your machine has low memory when this happens? And the standard IT support question, have you tried to update and reboot the computer? Has it worked better before, or is this a new installation?

I will check the configuration scheme to see if there is something that could be done simpler. 

Regards,
Kenneth

**Comment by mrmay-dev** [comment]
Thank you for the response! I've tried my hand at programming and understand how much work goes into a project like yours. I'm not very good at it, but I have fun. :) 

When opening the configuration page in different browsers, Chrome and Edge (same codebase base) are slow to respond. Firefox, on the other hand, remains responsive.

- **Edge (slow):** Version 99.0.1150.39 (Official build) beta (64-bit)
- **Chrome (slow):** Version 99.0.4844.51 (Official Build) (64-bit)
- **Firefox (normal):** 99.0b3 (64-bit)

Cheers,
Richard

**Comment by mrmay-dev** [comment]
Huh. Now it's fine. Something on my end. Maybe one of my extensions was slowing things down. I've found that the LanguageTool extension slows some pages down. I later found other config pages that were slow and then fine. Anyhow, thanks taking a look. I know it takes some time. 

FWIW I use the plugin to trigger random alarms that help me stay focused on tasks. It's like having my phone nag me about things I keep forgetting or putting off. (A trick for those of us with ADHD trick. lol).

```

        {
            "name": "RandomDelaySwitches",
            "delaySwitches": [
                {
                    "name": "Random 5",
                    "delay": 480,
                    "minDelay": 120,
                    "random": true,
                    "disableSensor": false,
                    "startOnReboot": false,
                    "singleActivation": false,
                    "repeats": 3
                }
            ],
            "platform": "RandomDelaySwitches"
        }
```

**Comment by kernie66** [comment]
Thanks! I hope it continues to work as it should. With only one random switch, it shouldn't be a problem.

Regards,
Kenneth
